# Certificates generation
- hosts: wi1
  roles:
    - role: "../roles/cyb3rhq/cyb3rhq-indexer"
      indexer_network_host: "{{ private_ip }}"
      perform_installation: false
  become: true
  vars:
    indexer_node_master: true
  tags:
    - generate-certs

# Cyb3rhq indexer cluster
- hosts: wi_cluster
  roles:
    - role: "../roles/cyb3rhq/cyb3rhq-indexer"
      indexer_network_host: "{{ private_ip }}"
  become: true
  become_user: root
  vars:
    indexer_node_master: true

- hosts: manager
  roles:
    - role: "../roles/cyb3rhq/ansible-cyb3rhq-manager"
  become: true
  become_user: root

- hosts: filebeat
  roles:
    - role: "../roles/cyb3rhq/ansible-filebeat-oss"
  become: true
  become_user: root

# Indexer + dashboard node
- hosts: dashboard
  roles:
    - role: "../roles/cyb3rhq/cyb3rhq-indexer"
    - role: "../roles/cyb3rhq/cyb3rhq-dashboard"
  become: true
  become_user: root
  vars:
    indexer_network_host: "{{ hostvars.dashboard.private_ip }}"
    indexer_node_master: false
    indexer_node_ingest: false
    indexer_node_data: false
    indexer_cluster_nodes: "{{ indexer_discovery_nodes }}"
    ansible_shell_allow_world_readable_temp: true
    cyb3rhq_api_credentials:
      - id: default
        url: https://{{ hostvars.master.private_ip }}
        port: 55000
        username: cyb3rhq
        password: cyb3rhq

- hosts: agent
  roles:
    - role: "../roles/cyb3rhq/ansible-cyb3rhq-agent"
      become: "{{ ansible_os_family != 'Windows' }}"
      become_user: root
