---
- block:
  - name: Copy Filebeat configuration.
    template:
      src: filebeat.yml.j2
      dest: "/etc/filebeat/filebeat.yml"
      owner: root
      group: root
      mode: 0400
    notify: restart filebeat

  - name: Fetch latest Cyb3rhq alerts template
    get_url:
      url: https://raw.githubusercontent.com/cyb3rhq/cyb3rhq/{{ cyb3rhq_template_branch }}/extensions/elasticsearch/7.x/cyb3rhq-template.json
      dest: "/etc/filebeat/cyb3rhq-template.json"
      owner: root
      group: root
      mode: 0400
    notify: restart filebeat

  tags:
  - configure
