---
- name: RedHat/CentOS/Fedora/Amazon Linux | Install Filebeats repo
  yum_repository:
    name: cyb3rhq_repo
    description: Cyb3rhq Repo
    baseurl: "{{ filebeatrepo.yum }}"
    gpgkey: "{{ filebeatrepo.gpg }}"
    gpgcheck: true
  changed_when: false
