# Copyright (C) 2015, Cyb3rhq Inc.
# Created by Cyb3rhq, Inc. <info@cyb3rhq.com>.
# This program is a free software; you can redistribute it and/or modify it under the terms of GPLv2

- hosts: localhost
  become: true
  become_user: "{{ current_user }}"
  tasks:
    - name: Test {{ test }} for {{ component }}
      command: "python3 -m pytest modules/testing/tests/test_{{component}}/test_{{ test }}.py  -v --cyb3rhq_version={{ cyb3rhq_version }} --cyb3rhq_revision={{ cyb3rhq_revision }}  --component={{ component }} --dependencies='{{ dependencies }}' --targets='{{ targets }}' --live={{ live }} -s"
      args:
        chdir: "{{ local_host_path }}"
